//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunshineAirlines1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightReservation()
        {
            this.FlightFoodReservations = new HashSet<FlightFoodReservation>();
        }
    
        public int ReservationId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string IDType { get; set; }
        public string IDTypeNumber { get; set; }
        public string CountryCode { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public string ETicketNumber { get; set; }
        public decimal Payment { get; set; }
        public int CabinTypeId { get; set; }
        public int UserId { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<int> SeatLayoutId { get; set; }
    
        public virtual CabinType CabinType { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightFoodReservation> FlightFoodReservations { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual SeatLayout SeatLayout { get; set; }
        public virtual User User { get; set; }
        public virtual Luggage Luggage { get; set; }
    }
}
