//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunshineAirlines1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDB : DbContext
    {
        public MyDB()
            : base("name=MyDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<CabinType> CabinTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FlightFood> FlightFoods { get; set; }
        public virtual DbSet<FlightFoodReservation> FlightFoodReservations { get; set; }
        public virtual DbSet<FlightReservation> FlightReservations { get; set; }
        public virtual DbSet<FlightStatu> FlightStatus { get; set; }
        public virtual DbSet<Luggage> Luggages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SeatLayout> SeatLayouts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
