//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunshineAirlines1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatLayout()
        {
            this.FlightReservations = new HashSet<FlightReservation>();
        }
    
        public int Id { get; set; }
        public int RowNumber { get; set; }
        public string ColumnName { get; set; }
        public int CabinTypeId { get; set; }
        public int AircraftId { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual CabinType CabinType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightReservation> FlightReservations { get; set; }
    }
}
